matrix:
    include:
       - language: julia
         julia: 0.6
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: nightly
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: 0.6
         os: linux
       - language: julia
         julia: nightly
         os: linux

       - language: julia
         julia: 0.6
         os: osx
       - language: julia
         julia: nightly
         os: osx

    allow_failures:
       - julia: nightly
       - os: linux

notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("SimpleDirectMediaLayer")); Pkg.add("SimpleDirectMediaLayer"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
