matrix:
    include:
       - language: julia
         julia: 0.7
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: 1.0
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: 0.7
         os: linux
       - language: julia
         julia: 1.0
         os: linux
       - language: julia
         julia: 0.7
         os: osx
       - language: julia
         julia: 1.0
         os: osx

    allow_failures:
       - os: linux

notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("SimpleDirectMediaLayer")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
