[general]
library_name = "libsdl2"
library_names = {"SDL2/SDL_mixer.h" = "libsdl2_mixer", "SDL2/SDL_image.h" = "libsdl2_image", "SDL2/SDL_ttf.h" = "libsdl2_ttf"}
output_file_path = "../src/LibSDL2.jl"
module_name = "LibSDL2"
jll_pkg_name = "SDL2_jll"
jll_pkg_extra = ["SDL2_mixer_jll", "SDL2_image_jll", "SDL2_ttf_jll"]
export_symbol_prefixes = ["TTF_", "IMG_", "Mix_", "SDL_", "MIX_", "RW_", "AUDIO_", "KMOD_", "HAVE_", ]
prologue_file_path = "./prologue.jl"
use_deterministic_symbol = true

printer_blacklist = [
    "SDL_MIN_SINT8",
    "SDL_MIN_SINT16",
    "SDL_MIN_SINT32",
    "SDL_MIN_SINT64",
    "SDL_ICONV_ERROR",
    "SDL_ICONV_E2BIG",
    "SDL_ICONV_EILSEQ",
    "SDL_ICONV_EINVAL",
    "SDL_TOUCH_MOUSEID",
    "SDL_PRIu64",
    "SDL_PRIx64",
    "SDL_PRIX64",
    "SDL_FILE",
    "SDL_LINE",
    "Mix_SetError",
    "Mix_GetError",
    "Mix_ClearError",
    "Mix_OutOfMemory",
    "IMG_SetError",
    "IMG_GetError",
    "TTF_SetError",
    "TTF_GetError",
    "_HAS_FALLTHROUGH",
    "SDL_PRIu32",
    "SDL_PRIs32",
    "SDL_PRIx32",
    "SDL_PRIX32",
    "SDL_SIZE_MAX",
    "SDL_FLT_EPSILON",
    "HAS_BUILTIN_BSWAP16",
    "HAS_BUILTIN_BSWAP32",
    "HAS_BUILTIN_BSWAP64",
    "HAS_BROKEN_BSWAP",
]


[codegen.macro]
macro_mode = "basic"

functionlike_macro_includelist = [
    "SDL_WINDOWPOS_UNDEFINED_DISPLAY",
    "SDL_WINDOWPOS_CENTERED_DISPLAY",
    "SDL_BUTTON",
    "SDL_VERSIONNUM",
]